import { randomUUID } from 'node:crypto';
import WebSocket, { WebSocketServer } from 'ws';
import { HOTBAR_SLOT_COUNT, INVENTORY_SLOT_COUNT, RESOURCE_NODES, SURVIVAL, startingInventory } from '../src/shared/survivalConfig.js';

const MAX_PLAYERS = 3;
const SPAWN_POINTS = [{x:0,z:3,rotation:Math.PI},{x:-3,z:-2,rotation:.6},{x:3,z:-2,rotation:-.6}];
const randomInt = ([min,max]) => Math.floor(Math.random() * (max - min + 1)) + min;

export function multiplayerPlugin() {
  return { name:'three-player-survival', configureServer(server) {
    const socketServer=new WebSocketServer({noServer:true}), rooms=new Map(), clients=new Set(); let nextRoomNumber=1;
    const send=(socket,message)=>{if(socket.readyState===WebSocket.OPEN)socket.send(JSON.stringify(message));};
    const broadcast=(room,message)=>room.players.forEach(({socket})=>send(socket,message));
    const roomList=()=>[...rooms.values()].map(room=>({id:room.id,name:room.name,players:room.players.size,maxPlayers:MAX_PLAYERS}));
    const broadcastLobby=()=>clients.forEach(client=>send(client.socket,{type:'servers',servers:roomList()}));
    const serializeInventory=client=>({resources:{...client.inventory.resources},tools:[...client.inventory.tools],inventorySlots:[...client.inventory.inventorySlots],hotbar:[...client.inventory.hotbar]});
    const sendInventory=client=>send(client.socket,{type:'inventory',inventory:serializeInventory(client)});
    const makeResources=()=>new Map(RESOURCE_NODES.map(definition=>[definition.id,{...definition,remaining:definition.type==='leaf'?1:SURVIVAL[definition.type].capacity,active:true,respawnAt:0,timer:null}]));
    const resourceSnapshot=room=>[...room.resources.values()].map(({id,type,remaining,active,respawnAt})=>({id,type,remaining,active,respawnAt}));
    const broadcastPlayers=room=>broadcast(room,{type:'players',players:[...room.players.values()].map(({id,x,z,rotation,pitch})=>({id,x,z,rotation,pitch}))});
    function resetPlayer(client){const start=startingInventory();client.inventory={resources:{...start.resources},tools:new Set(start.tools),inventorySlots:[...start.inventorySlots],hotbar:[...start.hotbar]};client.lastGatherAt=0;client.x=0;client.z=0;}
    const ownsItem=(client,item)=>Object.hasOwn(client.inventory.resources,item)?client.inventory.resources[item]>0:client.inventory.tools.has(item);
    function syncItemPresence(client,item){const owned=ownsItem(client,item),inventory=client.inventory.inventorySlots,hotbar=client.inventory.hotbar,placed=inventory.includes(item)||hotbar.includes(item);if(owned&&!placed){const empty=inventory.indexOf(null);if(empty>=0)inventory[empty]=item;}if(!owned){for(let i=0;i<inventory.length;i++)if(inventory[i]===item)inventory[i]=null;for(let i=0;i<hotbar.length;i++)if(hotbar[i]===item)hotbar[i]=null;}}
    function moveInventoryItem(client,update){const fromArea=update.fromArea,toArea=update.toArea,from=Number(update.fromIndex),to=Number(update.toIndex);if(!['inventory','hotbar'].includes(fromArea)||!['inventory','hotbar'].includes(toArea))return fail(client,'Invalid inventory move');const source=fromArea==='inventory'?client.inventory.inventorySlots:client.inventory.hotbar,target=toArea==='inventory'?client.inventory.inventorySlots:client.inventory.hotbar;if(!Number.isInteger(from)||!Number.isInteger(to)||from<0||to<0||from>=source.length||to>=target.length)return fail(client,'Invalid inventory slot');const item=source[from];if(!item||!ownsItem(client,item))return fail(client,'Item not available');[source[from],target[to]]=[target[to],source[from]];sendInventory(client);}
    function sendRoomState(client,room){sendInventory(client);send(client.socket,{type:'resources',resources:resourceSnapshot(room)});}
    function assignSpawn(client,room){const spawn=SPAWN_POINTS[room.players.size%SPAWN_POINTS.length];client.x=spawn.x;client.z=spawn.z;client.rotation=spawn.rotation;return {...spawn};}
    function removeFromRoom(client){if(!client.roomId)return;const room=rooms.get(client.roomId);room?.players.delete(client.id);client.roomId=null;if(room){broadcastPlayers(room);if(room.players.size===0){room.resources.forEach(node=>node.timer&&clearTimeout(node.timer));rooms.delete(room.id);}}broadcastLobby();}
    function scheduleRespawn(room,node){const delay=SURVIVAL[node.type].respawnMs;node.active=false;node.respawnAt=Date.now()+delay;node.timer=setTimeout(()=>{if(!rooms.has(room.id))return;node.active=true;node.respawnAt=0;node.remaining=node.type==='leaf'?1:SURVIVAL[node.type].capacity;broadcast(room,{type:'resource-update',resource:{id:node.id,type:node.type,active:true,remaining:node.remaining,respawnAt:0}});},delay);}
    function fail(client,reason){send(client.socket,{type:'action-error',reason});}
    function gather(client,update){const room=rooms.get(client.roomId);if(!room)return;const now=Date.now();if(now-client.lastGatherAt<SURVIVAL.hitCooldownMs)return fail(client,'Too fast');const node=room.resources.get(String(update.nodeId));if(!node||!node.active)return fail(client,'Resource is depleted');if(Math.hypot(client.x-node.x,client.z-node.z)>SURVIVAL.interactionRange+.75)return fail(client,'Move closer');
      if(node.type==='leaf'){const roomLeft=SURVIVAL.stackLimits.leaves-client.inventory.resources.leaves;if(roomLeft<=0)return fail(client,'Leaf stack is full');const amount=Math.min(SURVIVAL.leaf.reward,roomLeft);client.lastGatherAt=now;client.inventory.resources.leaves+=amount;syncItemPresence(client,'leaves');scheduleRespawn(room,node);broadcast(room,{type:'resource-update',resource:{id:node.id,type:node.type,active:false,remaining:0,respawnAt:node.respawnAt}});sendInventory(client);send(client.socket,{type:'gather-result',label:`+${amount} Leaf`});return;}
      const requested=String(update.tool||'stone'),owns=requested==='stone'?client.inventory.resources.stone>0:client.inventory.tools.has(requested);if(!owns)return fail(client,'Tool not owned');let rewardRange;
      if(node.type==='tree'){if(!['stone','axe'].includes(requested))return fail(client,'Use Stone or Axe');rewardRange=requested==='axe'?SURVIVAL.tree.axeReward:SURVIVAL.tree.stoneReward;}
      else {if(!['stone','pickaxe'].includes(requested))return fail(client,'Use Stone or Pickaxe');rewardRange=requested==='pickaxe'?SURVIVAL.rock.pickaxeReward:SURVIVAL.rock.stoneReward;}
      const resource=node.type==='tree'?'wood':'stone',roomLeft=SURVIVAL.stackLimits[resource]-client.inventory.resources[resource];if(roomLeft<=0)return fail(client,`${resource==='wood'?'Wood':'Stone'} stack is full`);client.lastGatherAt=now;broadcast(room,{type:'player-action',playerId:client.id,action:'gather',tool:requested});const amount=Math.min(randomInt(rewardRange),node.remaining,roomLeft);node.remaining-=amount;client.inventory.resources[resource]+=amount;syncItemPresence(client,resource);if(node.remaining<=0)scheduleRespawn(room,node);broadcast(room,{type:'resource-update',resource:{id:node.id,type:node.type,active:node.active,remaining:node.remaining,respawnAt:node.respawnAt}});sendInventory(client);send(client.socket,{type:'gather-result',label:`+${amount} ${resource==='wood'?'Wood':'Stone'}`,remaining:node.remaining});
    }
    function craft(client,recipeId){const recipe=SURVIVAL.recipes[recipeId];if(!recipe)return fail(client,'Unknown recipe');if(recipe.gives.tool&&client.inventory.tools.has(recipe.gives.tool))return fail(client,'Tool already crafted');if(recipe.gives.resource&&client.inventory.resources[recipe.gives.resource]+recipe.gives.amount>SURVIVAL.stackLimits[recipe.gives.resource])return fail(client,'Item stack is full');for(const [resource,cost] of Object.entries(recipe.costs))if(client.inventory.resources[resource]<cost)return fail(client,'Not enough materials');for(const [resource,cost] of Object.entries(recipe.costs)){client.inventory.resources[resource]-=cost;syncItemPresence(client,resource);}if(recipe.gives.tool){client.inventory.tools.add(recipe.gives.tool);syncItemPresence(client,recipe.gives.tool);}else{client.inventory.resources[recipe.gives.resource]+=recipe.gives.amount;syncItemPresence(client,recipe.gives.resource);}sendInventory(client);send(client.socket,{type:'craft-result',recipeId});}
    server.httpServer.on('upgrade',(request,socket,head)=>{const pathname=new URL(request.url||'/','http://localhost').pathname.replace(/\/$/,'');if(pathname!=='/ws')return;socketServer.handleUpgrade(request,socket,head,client=>socketServer.emit('connection',client));});
    socketServer.on('connection',socket=>{const client={id:randomUUID(),socket,roomId:null,x:0,z:0,rotation:0,pitch:0};resetPlayer(client);clients.add(client);send(socket,{type:'welcome',id:client.id});send(socket,{type:'servers',servers:roomList()});
      socket.on('message',raw=>{try{const update=JSON.parse(raw.toString());
        if(update.type==='create'){removeFromRoom(client);const room={id:`room-${nextRoomNumber++}`,name:String(update.name||'New server').slice(0,24),players:new Map(),resources:makeResources()};rooms.set(room.id,room);resetPlayer(client);client.roomId=room.id;const spawn=assignSpawn(client,room);room.players.set(client.id,client);send(socket,{type:'joined',room:{id:room.id,name:room.name},spawn});sendRoomState(client,room);broadcastPlayers(room);broadcastLobby();return;}
        if(update.type==='join'){const room=rooms.get(update.roomId);if(!room||room.players.size>=MAX_PLAYERS){send(socket,{type:'join-failed',reason:!room?'Server not found':'Server is full'});return;}removeFromRoom(client);resetPlayer(client);client.roomId=room.id;const spawn=assignSpawn(client,room);room.players.set(client.id,client);send(socket,{type:'joined',room:{id:room.id,name:room.name},spawn});sendRoomState(client,room);broadcastPlayers(room);broadcastLobby();return;}
        if(update.type==='leave'){removeFromRoom(client);send(socket,{type:'left'});return;}
        if(update.type==='state'&&client.roomId){const x=Number(update.x),z=Number(update.z);if(!Number.isFinite(x)||!Number.isFinite(z))return;const dx=x-client.x,dz=z-client.z,distance=Math.hypot(dx,dz),maxStep=1.5;if(distance>maxStep){client.x+=dx/distance*maxStep;client.z+=dz/distance*maxStep;}else{client.x=x;client.z=z;}client.rotation=Number(update.rotation)||0;client.pitch=Number(update.pitch)||0;broadcastPlayers(rooms.get(client.roomId));return;}
        if(update.type==='gather'&&client.roomId){gather(client,update);return;}if(update.type==='craft'&&client.roomId){craft(client,String(update.recipeId));return;}if(update.type==='inventory-move'&&client.roomId){moveInventoryItem(client,update);return;}
      }catch{socket.close();}});socket.on('close',()=>{removeFromRoom(client);clients.delete(client);});
    });
  }};
}
