import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { CONFIG } from '../config.js';
import { clone } from 'three/addons/utils/SkeletonUtils.js';
import { playerHeight } from '../shared/worldLayout.js';
import { preparePlayerModel } from '../player/preparePlayerModel.js';

export class RemotePlayers {
  constructor(scene, camera) { this.scene = scene; this.camera = camera; this.players = new Map(); this.template = null; new GLTFLoader().loadAsync(CONFIG.assets.player).then(gltf => { this.template = preparePlayerModel(gltf.scene); this.players.forEach(player => this.attachModel(player)); }).catch(console.warn); }
  sync(states, localId) {
    const active = new Set(states.filter(s => s.id !== localId).map(s => s.id));
    states.forEach(state => { if (state.id === localId) return; const nextX=Number(state.x)||0,nextZ=Number(state.z)||0,nextRotation=Number(state.rotation)||0;let remote=this.players.get(state.id);if(!remote)remote=this.create(state.id,state.nickname,nextX,nextZ,nextRotation);if(remote.userData.nickname!==state.nickname)this.setNickname(remote,state.nickname);remote.userData.moving=Math.hypot(nextX-remote.userData.target.x,nextZ-remote.userData.target.z)>.008;remote.userData.target.set(nextX,playerHeight(nextX,nextZ),nextZ);remote.userData.targetRotation=nextRotation; });
    this.players.forEach((player, id) => { if (!active.has(id)) { this.disposePlayer(player); this.scene.remove(player); this.players.delete(id); } });
  }
  create(id,nickname='Explorer',x=0,z=0,rotation=0) { const group=new THREE.Group();group.position.set(x,playerHeight(x,z),z);group.rotation.y=rotation;group.userData.target=new THREE.Vector3(x,playerHeight(x,z),z);group.userData.targetRotation=rotation;group.userData.actionTime=0;group.userData.walkTime=0;group.userData.moving=false;group.userData.visual=new THREE.Group();group.add(group.userData.visual);this.setNickname(group,nickname);this.attachModel(group);this.scene.add(group);this.players.set(id,group);return group; }
  setNickname(group,nickname){const value=String(nickname||'Explorer').slice(0,20);group.userData.nameplate?.material.map?.dispose();group.userData.nameplate?.material.dispose();group.userData.nameplate?.removeFromParent();const canvas=document.createElement('canvas'),context=canvas.getContext('2d');canvas.width=512;canvas.height=128;context.font='700 48px Arial';context.textAlign='center';context.textBaseline='middle';context.lineWidth=10;context.strokeStyle='rgba(10,18,13,.9)';context.strokeText(value,256,64);context.fillStyle='#fff4dd';context.fillText(value,256,64);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:false,depthWrite:false}));sprite.scale.set(2.8,.7,1);sprite.position.y=2.25;sprite.renderOrder=20;group.add(sprite);group.userData.nameplate=sprite;group.userData.nickname=value;}
  attachModel(group){if(!this.template||group.userData.visual.children.length)return;const model=clone(this.template);model.rotation.y=Math.PI;const height=new THREE.Box3().setFromObject(model).getSize(new THREE.Vector3()).y;model.scale.setScalar(1.8/Math.max(.01,height));model.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(model),center=bounds.getCenter(new THREE.Vector3());model.position.x-=center.x;model.position.z-=center.z;model.position.y-=bounds.min.y;model.rotation.y=Math.PI;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});group.userData.visual.add(model);model.updateMatrixWorld(true);const grounded=new THREE.Box3().setFromObject(model);group.userData.nameplate.position.y=grounded.getSize(new THREE.Vector3()).y+.35;}
  disposePlayer(player){const label=player.userData.nameplate;label?.material.map?.dispose();label?.material.dispose();}
  playAction(playerId){const player=this.players.get(playerId);if(player)player.userData.actionTime=.42;}
  update(delta) { const amount=1-Math.exp(-14*delta);this.players.forEach(player=>{player.position.lerp(player.userData.target,amount);const angleDelta=Math.atan2(Math.sin(player.userData.targetRotation-player.rotation.y),Math.cos(player.userData.targetRotation-player.rotation.y));player.rotation.y+=angleDelta*amount;const visual=player.userData.visual;if(player.userData.moving)player.userData.walkTime+=delta*9;if(player.userData.actionTime>0){player.userData.actionTime=Math.max(0,player.userData.actionTime-delta);const progress=1-player.userData.actionTime/.42,arc=Math.sin(progress*Math.PI);visual.rotation.y=-arc*.32;visual.rotation.z=0;visual.rotation.x=0;visual.position.z=-arc*.08;}else{const bob=player.userData.moving?Math.sin(player.userData.walkTime)*.025:0;visual.rotation.x=THREE.MathUtils.damp(visual.rotation.x,0,18,delta);visual.rotation.y=THREE.MathUtils.damp(visual.rotation.y,0,18,delta);visual.rotation.z=THREE.MathUtils.damp(visual.rotation.z,player.userData.moving?Math.sin(player.userData.walkTime*.5)*.025:0,18,delta);visual.position.y=THREE.MathUtils.damp(visual.position.y,bob,18,delta);visual.position.z=THREE.MathUtils.damp(visual.position.z,0,18,delta);}}); }
  clear() { this.players.forEach(player => {this.disposePlayer(player);this.scene.remove(player);}); this.players.clear(); }
}
